import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {useAccount} from './AccountContext.jsx';
import {apiRequest,apiUrl} from '../../api/api.js';
const statusLabels={sent:'Aceptado por Mercado Libre',failed:'Fallido',uncertain:'Resultado incierto',blocked:'Bloqueado por cupo',preparing:'Preparando',sending:'Enviando'};
export default function Account(){
  const {account,reload}=useAccount(),[accepted,setAccepted]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[activity,setActivity]=useState([]),[confirmation,setConfirmation]=useState('');
  useEffect(()=>{if(account.consentCurrent&&account.legalReady&&account.status==='active')apiRequest('/api/activity').then(setActivity).catch(()=>{});},[account.consentCurrent,account.legalReady,account.status]);
  const run=async(fn)=>{setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}};
  const consent=()=>run(async()=>{await apiRequest('/api/account/consent',{method:'POST',body:JSON.stringify({accepted:true,privacyVersion:account.legalVersion,termsVersion:account.legalVersion})});await reload();});
  const endSession=(path,method='POST',body)=>run(async()=>{await apiRequest(path,{method,...(body?{body:JSON.stringify(body)}:{})});window.location.assign('/login');});
  const download=()=>run(async()=>{
    const res=await fetch(apiUrl('/api/account/export'),{credentials:'include'});
    if(!res.ok)throw new Error('No se pudo exportar. Intentá más tarde.');
    const blob=await res.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='flowsell-mis-datos.json';a.click();URL.revokeObjectURL(url);
  });
  return <div className="page-stack"><header><span className="fs-eyebrow">Control y transparencia</span><h1>Mi cuenta y privacidad</h1><p>{account.nickname} · Mercado Libre ID {account.meliId}</p></header>
    {error&&<p className="form-alert form-alert--error" role="alert">{error}</p>}
    {!account.legalReady&&<section className="panel"><h2>Configuración legal pendiente</h2><p>El responsable de Flow Sell está completando los datos legales. Podés consultar tu cuenta, pero las operaciones están pausadas hasta que la documentación esté disponible.</p></section>}
    {!account.consentCurrent?<section className="panel fs-consent"><h2>Antes de empezar</h2><p>Leé cómo se usan los datos necesarios para gestionar tu cuenta y las condiciones del servicio. La autorización de Mercado Libre es independiente de esta aceptación.</p><div className="fs-inline-links"><Link to="/privacy" target="_blank">Política de privacidad ↗</Link><Link to="/terms" target="_blank">Términos y Condiciones ↗</Link></div><label className="fs-check"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>Leí y acepto ambos documentos, versión {account.legalVersion}, y autorizo el tratamiento para las funciones solicitadas.</span></label><button className="button button--primary" disabled={!accepted||busy||!account.legalReady} onClick={consent}>Aceptar y habilitar mi cuenta</button></section>:<p className="fs-success">Documentación vigente aceptada · versión {account.legalVersion}</p>}
    <section className="panel"><div className="panel__header"><h2>Consumo de {account.usage.month}</h2><Link to="/app/plans">Plan {account.plan.name} →</Link></div><div className="fs-usage-grid">{[
      ['Flujos configurados',account.usage.flows,account.plan.flows],['Plantillas',account.usage.templates,account.plan.templates],
      ['Intentos de mensaje',account.usage.messages,account.plan.messages],['Campañas',account.usage.campaigns,account.plan.campaigns],
      ['Almacenamiento (MB)',Math.ceil(account.usage.storageBytes/1024/1024),Math.round(account.plan.storageBytes/1024/1024)],
    ].map(([label,value,max])=><div className="fs-usage" key={label}><span>{label}</span><strong>{value} <small>/ {max}</small></strong><progress value={Math.min(value,max||1)} max={max||1}/>{value>max&&<small>Excede las capacidades actuales. Tus datos se conservan.</small>}</div>)}</div></section>
    <section className="panel"><div className="panel__header"><h2>Actividad de envíos</h2><button className="text-button" onClick={()=>run(async()=>setActivity(await apiRequest('/api/activity')))} disabled={busy||!account.consentCurrent||!account.legalReady}>Actualizar</button></div><p>Últimos 50 registros. Un resultado incierto necesita revisión antes de volver a enviar.</p>{activity.length?<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Fecha</th><th>Orden</th><th>Tipo</th><th>Resultado</th></tr></thead><tbody>{activity.map(a=><tr key={a._id}><td>{new Date(a.createdAt).toLocaleString('es-AR')}</td><td>{a.orderId}</td><td>{{initial:'Inicial',delayed:'Diferido',campaign:'Campaña','delivery-confirmation':'Confirmación de entrega'}[a.phase]||a.phase}</td><td>{statusLabels[a.status]||a.status}{a.reason==='MEDIA_MIGRATION_REQUIRED'&&' · Migración de imágenes pendiente'}</td></tr>)}</tbody></table></div>:<p>Todavía no hay envíos registrados.</p>}</section>
    <div className="fs-guide-grid"><section className="panel fs-prose"><h2>Tus datos</h2><p>Descargá un JSON con tu cuenta, configuraciones y registros. No incluye secretos de acceso. El archivo puede incluir datos de compradores de tus campañas; guardalo en un lugar privado.</p><button className="button button--secondary" onClick={download} disabled={busy}>Exportar mis datos</button><div className="fs-inline-links"><Link to="/privacy">Privacidad</Link><Link to="/terms">Términos</Link></div></section>
    <section className="panel fs-prose"><h2>Sesiones y conexión</h2><p>Podés cerrar todas tus sesiones. Desconectar además elimina los tokens guardados en Flow Sell y detiene las automatizaciones, conservando tus configuraciones.</p><div className="fs-action-stack"><button className="button button--secondary" onClick={()=>endSession('/api/account/sessions/revoke')} disabled={busy}>Cerrar todas las sesiones</button><button className="button button--secondary" onClick={()=>{if(window.confirm('¿Desconectar Mercado Libre y detener las automatizaciones?'))endSession('/api/account/disconnect');}} disabled={busy}>Desconectar Mercado Libre</button><a className="text-link" href={apiUrl('/api/auth/login')}>Reconectar mi cuenta</a></div><p>Para revocar también el permiso en Mercado Libre, quitá Flow Sell desde las aplicaciones autorizadas de esa plataforma.</p></section></div>
    <section className="panel fs-danger"><h2>Eliminar mi cuenta</h2><p>Se cierra el acceso inmediatamente y se inicia el borrado de cuenta, plantillas, asignaciones y archivos. Los mensajes ya enviados a Mercado Libre no se retiran. Si tenés un plan contratado por fuera de la app, pedí también su cancelación a soporte.</p><p>Para esta acción tenés que haber iniciado sesión en los últimos 15 minutos. Si no, cerrá sesión y volvé a entrar.</p><label className="form-field"><span>Escribí ELIMINAR MI CUENTA para confirmar</span><input value={confirmation} onChange={e=>setConfirmation(e.target.value)} autoComplete="off"/></label><button className="button fs-danger-button" disabled={busy||confirmation!=='ELIMINAR MI CUENTA'} onClick={()=>endSession('/api/account','DELETE',{confirmation})}>Solicitar eliminación definitiva</button></section>
  </div>;
}
