import {useCallback,useEffect,useState} from 'react';
import {Navigate} from 'react-router-dom';
import {apiRequest} from '../../api/api.js';
import {useAccount} from './AccountContext.jsx';
export default function Admin(){
  const {account}=useAccount(),[verified,setVerified]=useState(false),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[overview,setOverview]=useState(null),[listing,setListing]=useState({users:[]}),[requests,setRequests]=useState([]),[audit,setAudit]=useState([]),[page,setPage]=useState(1),[search,setSearch]=useState(''),[filter,setFilter]=useState(''),[editing,setEditing]=useState(null),[plan,setPlan]=useState('free'),[expires,setExpires]=useState('');
  const load=useCallback(async()=>{
    try{const [o,u,r,a]=await Promise.all([apiRequest('/api/admin/overview'),apiRequest('/api/admin/users?page='+page+(filter?'&meliId='+encodeURIComponent(filter):'')),apiRequest('/api/admin/requests'),apiRequest('/api/admin/audit')]);setOverview(o);setListing(u);setRequests(r);setAudit(a);setError('');}
    catch(e){if(e.payload?.code==='ADMIN_MFA_REQUIRED')setVerified(false);setError(e.message);}
  },[page,filter]);
  useEffect(()=>{if(verified)load();},[verified,load]);
  useEffect(()=>{if(account.isAdmin)apiRequest('/api/admin/overview').then(data=>{setOverview(data);setVerified(true);}).catch(()=>{});},[account.isAdmin]);
  if(!account.isAdmin)return <Navigate to="/app" replace/>;
  const verify=async e=>{e.preventDefault();setBusy(true);setError('');try{await apiRequest('/api/admin/verify',{method:'POST',body:JSON.stringify({code})});setVerified(true);setCode('');}catch(err){setError(err.message);}finally{setBusy(false);}};
  const save=async e=>{e.preventDefault();if(!window.confirm('¿Cambiar el plan de '+editing.nickname+' (ML '+editing.meliId+') a '+plan+'?'))return;setBusy(true);setError('');try{await apiRequest('/api/admin/users/'+editing._id+'/plan',{method:'PATCH',body:JSON.stringify({plan,expiresAt:expires?new Date(expires+'T23:59:59.999Z').toISOString():null})});setEditing(null);await load();}catch(err){if(err.payload?.code==='ADMIN_MFA_REQUIRED')setVerified(false);setError(err.message);}finally{setBusy(false);}};
  return <div className="page-stack"><header><span className="fs-eyebrow">Acceso del titular</span><h1>Administración</h1><p>Información operativa y gestión manual de planes. No se muestran contenidos ni credenciales.</p></header>
    {error&&<p className="form-alert form-alert--error" role="alert">{error}</p>}
    {!verified?<form className="panel fs-admin-verify form-stack" onSubmit={verify}><h2>Verificá tu identidad</h2><p>Ingresá el código de seis dígitos de tu aplicación de autenticación. El acceso administrativo dura 15 minutos.</p><label className="form-field"><span>Código del autenticador</span><input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/></label><button className="button button--primary" disabled={busy}>Verificar acceso</button></form>:<>
      {!overview?.legalReady&&<p className="form-alert form-alert--error">Completá y revisá los datos legales de la instalación antes de abrir el servicio.</p>}
      <section className="fs-admin-metrics">{Object.entries({Cuentas:overview?.users,Plantillas:overview?.templates,Flujos:overview?.flows,Archivos:overview?.files,'MB almacenados':Math.ceil((overview?.storageBytes||0)/1024/1024),Campañas:overview?.jobs,Envíos:overview?.sent,'Fallidos o inciertos':overview?.failed,Solicitudes:overview?.requests}).map(([label,value])=><article className="panel" key={label}><span>{label}</span><strong>{value??'…'}</strong></article>)}</section>
      <section className="panel"><div className="panel__header"><h2>Cuentas</h2><button className="text-button" onClick={load}>Actualizar</button></div><form className="fs-search-form" onSubmit={e=>{e.preventDefault();setPage(1);setFilter(search);}}><label className="sr-only" htmlFor="admin-search">ID de Mercado Libre</label><input id="admin-search" inputMode="numeric" pattern="[0-9]*" placeholder="Buscar ID de Mercado Libre" value={search} onChange={e=>setSearch(e.target.value)}/><button className="button button--secondary">Buscar</button></form>
      <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Cuenta</th><th>ID ML</th><th>Plan efectivo</th><th>Plantillas / flujos</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{listing.users.map(u=><tr key={u._id}><td>{u.nickname}<small className="fs-block">{u._id}</small></td><td>{u.meliId}</td><td>{u.effectivePlan}{u.planExpiresAt&&<small className="fs-block">Vence {new Date(u.planExpiresAt).toLocaleDateString('es-AR')}</small>}</td><td>{u.templates} / {u.flows}</td><td>{u.status||'active'}</td><td><button className="button button--small button--secondary" disabled={u.status==='deleting'} onClick={()=>{setEditing(u);setPlan(u.effectivePlan);setExpires(u.planExpiresAt?.slice(0,10)||'');}}>Cambiar plan</button></td></tr>)}</tbody></table></div><div className="fs-pagination"><button className="button button--ghost" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>Página {page} · {listing.total||0} cuentas</span><button className="button button--ghost" disabled={page*30>=(listing.total||0)} onClick={()=>setPage(p=>p+1)}>Siguiente</button></div></section>
      {editing&&<form className="panel form-stack" onSubmit={save}><h2>Plan de {editing.nickname}</h2><p>Verificá la cuenta y las condiciones acordadas antes de confirmar. No se procesa ningún cobro.</p><label className="form-field"><span>Plan</span><select value={plan} onChange={e=>setPlan(e.target.value)}><option value="free">Gratuito</option><option value="premium">Premium</option><option value="plus">Plus</option></select></label><label className="form-field"><span>Vencimiento al final del día UTC (opcional)</span><input type="date" value={expires} onChange={e=>setExpires(e.target.value)} disabled={plan==='free'}/><small>Vacío: no vence automáticamente. Para mensual, indicá el fin del período acordado.</small></label><div className="fs-inline-links"><button className="button button--primary" disabled={busy}>Confirmar cambio</button><button className="button button--ghost" type="button" onClick={()=>setEditing(null)}>Cancelar</button></div></form>}
      <section className="panel"><h2>Solicitudes pendientes</h2>{requests.length?<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Referencia</th><th>Cuenta interna</th><th>Plan</th><th>Fecha</th></tr></thead><tbody>{requests.map(r=><tr key={r._id}><td>{r._id}</td><td>{r.owner?.nickname||'Cuenta eliminada'}<small className="fs-block">ML {r.owner?.meliId||'—'} · {r.owner?._id||'—'}</small></td><td>{r.plan}</td><td>{new Date(r.createdAt).toLocaleDateString('es-AR')}</td></tr>)}</tbody></table></div>:<p>No hay solicitudes pendientes.</p>}</section>
      <section className="panel"><h2>Auditoría reciente</h2><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Fecha</th><th>Acción</th><th>Cuenta</th><th>Plan solicitado</th></tr></thead><tbody>{audit.map(a=><tr key={a._id}><td>{new Date(a.createdAt).toLocaleString('es-AR')}</td><td>{a.action}</td><td>{a.target}</td><td>{a.details?.plan||'—'}</td></tr>)}</tbody></table></div></section>
    </>}
  </div>;
}
