import {useState} from 'react';
import {Link} from 'react-router-dom';
import {FiBookOpen,FiSearch} from 'react-icons/fi';
import {SUPPORT_WHATSAPP_URL} from '../../constants/support.js';
const sections=[
  {name:'Resumen',to:'/app',was:'Inicio del panel',text:'Reúne ventas pagadas, ticket promedio, publicaciones y estado de tus flujos. Muestra el período disponible en tu plan; la facturación es bruta y no equivale a ganancia neta.',steps:['Revisá las ventas recientes.','Usá los accesos para continuar con una tarea.']},
  {name:'Publicaciones',to:'/app/products',was:'Productos / listado de publicaciones',text:'Consulta tu catálogo de Mercado Libre. Desde Configurar mensajes elegís las plantillas iniciales de cada publicación o variante. El catálogo se carga por tandas para evitar consultas excesivas.',steps:['Buscá la publicación por título o ID.','Seleccioná mensajes y, si corresponde, una variante.','Guardá. Un flujo habilitado puede ejecutarse ante una venta pagada.']},
  {name:'Flujos automáticos',to:'/app/automations',was:'Productos guardados / Saved',text:'Administra las asignaciones que ya creaste: orden de mensajes, variantes y mensajes diferidos. Podés pausar un flujo sin borrar su configuración. Si bajás de plan, sólo se ejecuta la cantidad permitida.',steps:['Revisá qué flujos figuran activos.','Ordená o quitá plantillas.','Desde Premium, agregá un segundo mensaje y una espera de 1 a 72 horas.','La confirmación de entrega es optativa y sólo se intenta en órdenes sin envío físico. Activala únicamente cuando corresponda.']},
  {name:'Plantillas',to:'/app/templates',was:'Plantillas',text:'Tu biblioteca de mensajes reutilizables. Cada plantilla admite 350 caracteres y hasta cinco imágenes de 2 MB. Modificarla afecta a los próximos envíos que la utilicen.',steps:['Poné un nombre que reconozcas fácilmente.','Escribí el mensaje y adjuntá imágenes si las necesitás.','Asignala a una publicación o campaña.','Las imágenes se normalizan y guardan privadas. No subas documentos, contraseñas ni información sensible.']},
  {name:'Campañas',to:'/app/campaigns',was:'Tracking / seguimiento de compradores',text:'Disponible desde Premium. Encuentra compradores de tus ventas pagadas para comunicaciones posventa permitidas por Mercado Libre. No habilita envíos publicitarios indiscriminados ni garantiza que la plataforma permita contactar una orden antigua.',steps:['Elegí publicaciones y período.','Buscá y revisá la audiencia; hay un contacto por comprador.','Seleccioná las plantillas y confirmá el envío.','Revisá el estado. Un resultado incierto no se reintenta automáticamente para evitar duplicados.']},
  {name:'Ventas y estadísticas',to:'/app/statistics',was:'Nueva en el rediseño',text:'Muestra facturación bruta, órdenes pagadas, unidades, compradores únicos, evolución diaria y productos vendidos. Los datos provienen de tu cuenta de Mercado Libre y pueden cambiar por actualizaciones de la plataforma.',steps:['Elegí un período dentro de tu historial disponible.','Aplicá el filtro.','Desde Premium, exportá un CSV compatible con Excel.','Guardá el archivo con cuidado: puede incluir identificadores de tus compradores.']},
  {name:'Mi plan',to:'/app/plans',was:'Nueva',text:'Compara capacidades y registra solicitudes de cambio. La contratación se coordina por WhatsApp con tu cuenta ya identificada. No hay pago ni renovación automática dentro de la app.',steps:['Compará Gratuito, Premium y Plus.','Solicitá un cambio.','Continuá con soporte usando la referencia.']},
  {name:'Mi cuenta y privacidad',to:'/app/account',was:'Nueva',text:'Muestra tus cupos, documentos aceptados y actividad de envíos. Permite exportar datos, cerrar sesiones, desconectar Mercado Libre o solicitar la eliminación de la cuenta.',steps:['Aceptá los documentos vigentes para operar.','Consultá el consumo del mes.','Para eliminar la cuenta, volvé a iniciar sesión y confirmá la frase indicada.']},
  {name:'Administración',to:'/app/admin',was:'Nueva · sólo el titular de Flow Sell',text:'Panel reservado a las cuentas autorizadas por el titular y protegido por un autenticador. Muestra métricas operativas, solicitudes y cambios de plan; no permite leer mensajes, imágenes, tokens ni datos de compradores.',steps:['Verificá el código de tu autenticador.','Buscá el ID de cuenta indicado en la solicitud.','Confirmá el plan y vencimiento. El cambio queda registrado.']},
];
export default function Guide({publicPage=false}) {
  const [search,setSearch]=useState('');
  return <main className={publicPage?'fs-public-page':'page-stack'}>{publicPage&&<Link to="/login">← Volver a Flow Sell</Link>}
    <header><span className="fs-eyebrow"><FiBookOpen/> Centro de ayuda</span><h1>Una guía para cada paso</h1><p>Conocé qué hace cada sección y cómo empezar a usar tu espacio de trabajo.</p></header>
    <section className="panel fs-getting-started"><h2>Tu primera automatización</h2><ol><li>Conectá Mercado Libre y aceptá los documentos del servicio.</li><li>Creá una plantilla de agradecimiento en Plantillas.</li><li>Asignala desde Publicaciones y revisá el flujo.</li><li>Ante una venta pagada, verificá la actividad en Mi cuenta. No se procesan ventas anteriores al alta de un flujo por una búsqueda manual.</li></ol></section>
    <label className="fs-guide-search"><FiSearch/><span className="sr-only">Buscar una sección</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar una sección o una tarea…"/></label>
    <div className="fs-guide-grid">{sections.filter(s=>(s.name+' '+s.text).toLowerCase().includes(search.toLowerCase())).map(s=><article className="panel fs-guide-card" key={s.name}><span className="fs-tag">{s.was}</span><h2>{s.name}</h2><p>{s.text}</p><ol>{s.steps.map(step=><li key={step}>{step}</li>)}</ol>{s.name!=='Administración'&&<Link to={publicPage?'/login':s.to}>Ir a la sección →</Link>}</article>)}</div>
    <section className="panel fs-prose"><h2>¿Por qué no se envió un mensaje?</h2><p>Comprobá que el flujo esté habilitado, la venta esté pagada, el plan tenga cupo, tu conexión esté vigente y hayas aceptado los documentos actuales. Mercado Libre puede restringir la mensajería. En Mi cuenta podés distinguir enviados, bloqueados, fallidos e inciertos; “enviado” significa que la API aceptó la solicitud, no que el comprador la haya leído.</p><a className="button button--secondary" href={SUPPORT_WHATSAPP_URL} target="_blank" rel="noreferrer">Consultar a soporte</a></section>
  </main>;
}
