import {Link} from 'react-router-dom';
import {usePublicConfig} from './AccountContext.jsx';
export default function Legal({kind='privacy'}) {
  const {legal,loading,error}=usePublicConfig();
  if(loading)return <main className="fs-public-page" role="status">Cargando documentación…</main>;
  if(error)return <main className="fs-public-page" role="alert">No pudimos cargar los datos del responsable. Intentá nuevamente más tarde.</main>;
  const privacy=kind==='privacy';
  return <main className="fs-public-page fs-prose"><Link to="/login">← Volver a Flow Sell</Link><header><span className="fs-eyebrow">Documentación del servicio · versión {legal.version}</span><h1>{privacy?'Política de privacidad':'Términos y Condiciones'}</h1></header>
    {!legal.ready&&<p className="form-alert form-alert--error" role="status">Documento en preparación. Falta completar y validar los datos del responsable. Las altas comerciales y la aceptación del servicio no están habilitadas.</p>}
    <section className="panel"><h2>Responsable y contacto</h2><p>Flow Sell es operado por {legal.name||'[Nombre legal pendiente]'}. Domicilio: {legal.address||'[Domicilio pendiente]'}.{legal.taxId?' Identificación tributaria: '+legal.taxId+'.':''}</p><p>Consultas legales y de privacidad: {legal.email?<a href={'mailto:'+legal.email}>{legal.email}</a>:'[Correo de privacidad pendiente]'}. Soporte: <a href="https://wa.me/5492342510893" target="_blank" rel="noreferrer">+54 9 2342 510893</a>.</p></section>
    {privacy?<Privacy legal={legal}/>:<Terms/>}
    <footer className="fs-legal-footer"><Link to={privacy?'/terms':'/privacy'}>{privacy?'Términos y Condiciones':'Política de privacidad'}</Link><Link to="/guide">Guía de uso</Link></footer>
  </main>;
}
function Privacy({legal}) {return <>
  <h2>1. Alcance y finalidades</h2><p>Esta política describe el uso de datos para conectar una cuenta de vendedor, ejecutar las automatizaciones que configura, preparar comunicaciones posventa, consultar estadísticas, administrar planes y prestar soporte. También tratamos los registros necesarios para proteger el servicio, prevenir abuso y atender derechos. No vendemos bases de datos, no usamos el contenido de mensajes para publicidad propia ni para entrenar modelos de inteligencia artificial.</p>
  <h2>2. Qué datos se utilizan</h2><p>Mercado Libre proporciona el identificador de cuenta, nombre de usuario, correo y credenciales de acceso delegadas. Guardamos estas credenciales cifradas para consultar la API y renovar la conexión; no solicitamos la contraseña de Mercado Libre. Guardamos las plantillas, imágenes, asignaciones, preferencias, plan, consumos y aceptación de documentos que generás en Flow Sell.</p><p>Para ventas y mensajería consultamos datos de publicaciones, órdenes pagadas, identificador y apodo del comprador, fechas, cantidades e importes. No necesitamos tarjetas, contraseñas de compradores, documentos de identidad, domicilios de entrega ni datos de salud. Las consultas a la API pueden contener campos adicionales, que no se incluyen en los registros operativos persistidos por esta versión. No incluyas datos sensibles en mensajes, imágenes o solicitudes de soporte.</p>
  <h2>3. Fundamento y decisiones del usuario</h2><p>Los datos necesarios permiten prestar el servicio solicitado y cumplir la relación contractual, con la información y el consentimiento que correspondan bajo la Ley 25.326. La aceptación de los documentos se registra por versión y fecha. La autorización OAuth habilita acceso técnico a Mercado Libre; no reemplaza esta política, los términos ni los deberes de información del vendedor hacia sus compradores.</p><p>Conectar la cuenta e informar datos correctos es necesario para usar las funciones. Adjuntar imágenes, solicitar un plan o usar WhatsApp es opcional. Si no conectás la cuenta o retirás la autorización, no podremos ejecutar automatizaciones. Podés consultar los documentos sin iniciar sesión.</p>
  <h2>4. Vendedor y datos de compradores</h2><p>El vendedor decide las publicaciones, mensajes, destinatarios y finalidades de sus comunicaciones; debe tener una base válida, informar a sus compradores cuando corresponda y cumplir las reglas de Mercado Libre. En esas operaciones Flow Sell procesa datos por instrucciones del vendedor, limitadas a las funciones contratadas. Para la administración y seguridad de su propio servicio, Flow Sell actúa como responsable. El alcance del encargo se detalla también en los términos.</p>
  <h2>5. Proveedores y destinatarios</h2><table><thead><tr><th>Proveedor</th><th>Función y datos</th></tr></thead><tbody><tr><td>Mercado Libre</td><td>Identificación OAuth, catálogo, órdenes y recepción de los mensajes e imágenes que enviás.</td></tr><tr><td>Render</td><td>Ejecución del servidor, infraestructura, logs técnicos y colas en Key Value; éstas contienen referencias y tareas operativas.</td></tr><tr><td>Proveedor de MongoDB</td><td>Base de cuentas, credenciales cifradas, plantillas, asignaciones, sesiones, audiencias, cuotas y auditoría. La ubicación concreta se indica a continuación.</td></tr><tr><td>Cloudinary</td><td>Almacenamiento y procesamiento de imágenes privadas adjuntas a plantillas.</td></tr><tr><td>WhatsApp / Meta</td><td>Canal opcional de soporte y contratación; recibe lo que decidas enviar al abrir la conversación.</td></tr></tbody></table><p>No compartimos contenido entre cuentas. El panel de administración muestra identificadores, apodos, planes y cantidades operativas, sin mensajes, imágenes ni información de compradores. El personal autorizado puede necesitar acceso excepcional a sistemas para resolver incidentes, sujeto a deber de confidencialidad y control de accesos. Podemos responder a requerimientos válidos de autoridades dentro de la ley.</p>
  <h2>6. Ubicación y transferencias internacionales</h2><p>Infraestructura y ubicaciones declaradas: {legal.regions||'[Pendiente de declarar proveedor MongoDB, regiones y países de Render, MongoDB y Cloudinary]'}. Los proveedores internacionales y sus subencargados pueden tratar datos fuera de Argentina. Antes de operar, el responsable debe verificar los destinos, contratos y garantías correspondientes, incluyendo cláusulas adecuadas cuando el destino no tenga protección reconocida. Podés solicitar información sobre los proveedores y las garantías al contacto de privacidad. Esta política no equivale a afirmar que se ha obtenido una certificación de la AAIP.</p>
  <h2>7. Seguridad y cookies</h2><p>La aplicación aplica permisos por cuenta, validación de solicitudes, límites de uso, cifrado de tokens con AES-256-GCM y controles de acceso a los archivos. Las sesiones usan cookies necesarias HTTPOnly y SameSite=Lax, con Secure bajo HTTPS en producción. La sesión vence tras 24 horas de inactividad y exige nuevo acceso como máximo a los siete días. No incorporamos cookies publicitarias ni analítica de terceros en esta versión. Las fuentes se sirven desde la propia aplicación. La carga de imágenes de catálogo de Mercado Libre puede comunicar datos técnicos de conexión a ese proveedor.</p><p>La infraestructura procesa IP, hora, errores y otros datos técnicos para brindar y proteger el servicio. Los límites de solicitudes guardan identificadores derivados por plazos breves, no cuerpos ni credenciales. Ningún sistema puede prometer invulnerabilidad. Ante un incidente evaluaremos alcance, contención y las comunicaciones que correspondan.</p>
  <h2>8. Conservación y eliminación</h2><p>Cuenta, plantillas y asignaciones se conservan mientras mantengas el servicio. Las audiencias de campañas vencen a los 90 días; avisos recibidos a los 30 días; auditoría administrativa a los 180 días; consumos y comprobantes mínimos de envío a los 400 días para evitar duplicados y resolver incidencias. Los índices de vencimiento se ejecutan de forma asíncrona y no eliminan documentos exactamente al segundo del vencimiento. Las colas tienen retención limitada según tipo de tarea.</p><p>Desconectar elimina de nuestra cuenta las credenciales y frena futuras ejecuciones, manteniendo tus configuraciones. Eliminar la cuenta cierra el acceso y solicita el borrado de los datos y archivos; si un proveedor falla, se reintenta y se atiende la incidencia. Los respaldos protegidos deben rotar en un máximo de 30 días según la política operativa configurada por el responsable; no se reutilizan para nuevas finalidades. Las retenciones legalmente obligatorias, si correspondieran, se limitan a los datos necesarios y se informan.</p><p>Eliminar una imagen de Flow Sell no retira las copias de mensajes ya enviados a Mercado Libre, descargadas por destinatarios o guardadas por vos. La desvinculación definitiva del permiso se realiza también en las aplicaciones autorizadas de Mercado Libre. Los archivos exportados quedan bajo tu control.</p>
  <h2>9. Derechos y consultas</h2><p>Podés solicitar información, acceso, rectificación, actualización, supresión y retiro del consentimiento cuando corresponda. Mi cuenta permite exportar tus datos y solicitar la eliminación. Para corregir datos importados, actualizalos en Mercado Libre y reconectá; para otros pedidos escribí al correo de privacidad. Verificaremos tu identidad de forma proporcionada, sin pedir contraseñas ni tokens.</p><p>La AAIP informa un plazo de diez días corridos para responder pedidos de acceso y cinco días hábiles para rectificar, actualizar o suprimir datos. El acceso es gratuito al menos cada seis meses, sin perjuicio de los supuestos de interés legítimo. Podés presentar un reclamo ante la <a href="https://www.argentina.gob.ar/aaip/datospersonales/derechos" target="_blank" rel="noreferrer">Agencia de Acceso a la Información Pública</a> si tus derechos no son atendidos.</p>
  <h2>10. Cambios</h2><p>Publicaremos una nueva versión ante cambios relevantes y pediremos aceptación antes de reanudar operaciones que la requieran. No usaremos tus datos para una finalidad incompatible sin la información y base legal correspondientes.</p>
 </>;}
function Terms(){return <>
  <h2>1. Objeto y aceptación</h2><p>Flow Sell es un servicio de gestión para vendedores con cuenta de Mercado Libre. Permite configurar mensajes posventa, administrar plantillas y flujos, consultar ventas y preparar campañas permitidas. Para operar debés ser mayor de edad, tener capacidad para contratar y autorización sobre la cuenta conectada. La aceptación expresa de esta versión queda registrada junto con tu cuenta y fecha.</p>
  <h2>2. Cuenta y uso autorizado</h2><p>Debés proteger tus accesos, mantener información correcta y avisar si detectás uso indebido. Cada cuenta accede a sus propios recursos. No podés intentar acceder a datos de terceros, compartir credenciales de infraestructura, eludir cupos, explotar vulnerabilidades, cargar código malicioso o utilizar el servicio para fines ilícitos.</p><p>Flow Sell no forma parte de Mercado Libre ni está avalado por éste salvo acuerdo expreso separado. El acceso y la mensajería dependen de las autorizaciones, disponibilidad, límites y reglas de su plataforma.</p>
  <h2>3. Planes, precios y contratación</h2><p>Existen los planes Gratuito, Premium y Plus con las capacidades publicadas en Mi plan y en la página de acceso. La contratación de planes pagos se coordina por soporte después de iniciar sesión y registrar una solicitud. No se almacenan tarjetas ni se procesan pagos o débitos automáticos dentro de esta app. Antes de pagar se confirmarán el importe final, moneda, impuestos aplicables, duración, inicio, renovación y condiciones de cancelación.</p><p>La solicitud por sí sola no activa un plan ni constituye confirmación de pago. El administrador registra la activación y, cuando corresponda, su vencimiento. No habrá modificaciones retroactivas de un período pago acordado. Las nuevas condiciones se comunicarán antes de una renovación.</p>
  <h2>4. Cupos y ejecución</h2><p>Los cupos de mensajes y campañas se computan por mes calendario en UTC. Cada intento de enviar una plantilla a un destinatario consume una unidad de mensaje, aunque el proveedor lo rechace. Las búsquedas de audiencia están limitadas a cinco veces el cupo de campañas mensual. Una campaña admite hasta diez plantillas y el número de compradores indicado en el plan. Los límites técnicos de API, archivos, consultas y solicitudes protegen la continuidad del servicio.</p><p>Una baja de plan conserva los datos y deja activos los flujos habilitados más antiguos hasta el límite correspondiente. No se crean recursos por encima del cupo ni se ejecutan funciones excluidas. Vencido un plan pago, la cuenta pasa a las capacidades gratuitas. Los mensajes bloqueados o no enviados no se reenvían por el mero cambio de plan.</p>
  <h2>5. Responsabilidad sobre mensajes e imágenes</h2><p>El vendedor es responsable del contenido, las finalidades y los destinatarios seleccionados, de los derechos sobre imágenes y del cumplimiento de las normas de posventa, publicidad y protección de datos. No se permite spam, hostigamiento, contenido ilícito, documentos sensibles, secretos de acceso ni uso de campañas para eludir restricciones de Mercado Libre. Podremos pausar el acceso por abuso, incidentes o incumplimientos, informando los motivos y una vía de revisión cuando ello no afecte una investigación o la seguridad.</p><p>La confirmación de entrega es opcional y sólo debe activarse cuando refleje la realidad de la operación. Que una API acepte un mensaje no prueba su lectura ni su efecto comercial. Los reportes muestran importes brutos de operaciones pagadas, pueden actualizarse y no sustituyen contabilidad, facturación ni conciliación.</p>
  <h2>6. Tratamiento por encargo</h2><p>Para los datos de compradores que el vendedor decide tratar, éste encomienda a Flow Sell únicamente las operaciones necesarias para ejecutar las funciones configuradas durante la vigencia del servicio: consulta, organización, almacenamiento temporal, transmisión y supresión. Las categorías habituales son identificadores, apodos, órdenes, publicaciones, importes, mensajes e imágenes aportadas. Se excluye solicitar datos sensibles.</p><p>Flow Sell se compromete a seguir instrucciones documentadas compatibles con el servicio y la ley, mantener confidencialidad, aplicar medidas de seguridad, restringir accesos y ayudar razonablemente con pedidos de derechos e incidentes. No explotará esos datos con fines propios de publicidad. Los proveedores y transferencias se describen en la política; los cambios relevantes se informarán con antelación razonable. Al finalizar, los datos podrán exportarse y se eliminarán según los plazos informados y obligaciones aplicables. Requisitos adicionales de auditoría, subencargados o conservación deben documentarse por escrito antes de contratar.</p>
  <h2>7. Disponibilidad e incidencias</h2><p>Adoptamos medidas razonables para la continuidad, sin prometer disponibilidad ininterrumpida, invulnerabilidad ni resultados comerciales. Pueden existir interrupciones de proveedores, mantenimiento y restricciones de Mercado Libre. Los envíos con resultado incierto no se repiten automáticamente, para reducir duplicados; el vendedor debe revisar el estado antes de volver a contactar al comprador. Ante una incidencia comunicaremos el estado y procuraremos corregirla.</p><p>Ninguna disposición limita responsabilidades que la ley no permita excluir, ni derechos irrenunciables que pudieran corresponder al usuario. Los alcances de servicio y remedios de un plan pago se fijarán en su confirmación comercial.</p>
  <h2>8. Cancelación y salida</h2><p>Podés pedir la no renovación por soporte en cualquier momento. Las condiciones de finalización y reintegros se informarán antes del pago y respetarán la normativa aplicable. Desconectar Mercado Libre frena nuevas operaciones; eliminar la cuenta solicita el borrado y no equivale por sí mismo a resolver cobros externos pendientes. Para una baja integral, solicitá también la cancelación comercial a soporte. Si hubiera derechos de revocación o protección del consumidor aplicables, prevalecen sobre estos términos y pueden ejercerse por el contacto informado.</p>
  <h2>9. Propiedad intelectual</h2><p>Conservás los derechos sobre tus contenidos. Otorgás únicamente el permiso necesario para almacenarlos, procesarlos y enviarlos por las funciones que elegís. El software y marca de Flow Sell y los activos de terceros conservan sus respectivos titulares. La suscripción otorga acceso al servicio, sin transferir propiedad del software.</p>
  <h2>10. Cambios, ley y contacto</h2><p>Rige la legislación argentina, sin perjuicio de normas imperativas que resulten aplicables. Las controversias se atenderán primero mediante el contacto informado y, de no resolverse, ante los tribunales legalmente competentes, sin imponer renuncias a fueros protectores. Los cambios sustanciales se publicarán con versión y fecha y se solicitará nueva aceptación. Consultá también la <Link to="/privacy">Política de privacidad</Link>.</p>
 </>;}
