import {useEffect} from 'react';
import {Link,useNavigate,useSearchParams} from 'react-router-dom';
import {FiArrowRight,FiShield,FiZap,FiMessageCircle,FiBarChart2,FiLayers} from 'react-icons/fi';
import BrandMark from '../common/BrandMark.jsx';
import {apiUrl} from '../../api/api.js';
import {PlanCards} from '../account/Plans.jsx';
import {SUPPORT_WHATSAPP_URL} from '../../constants/support.js';
export default function Landing({isAuthenticated}){
  const navigate=useNavigate(),[params]=useSearchParams();
  useEffect(()=>{if(isAuthenticated)navigate('/app',{replace:true});},[isAuthenticated,navigate]);
  return <main className="fs-landing"><div className="fs-landing-top"><nav className="fs-landing-nav" aria-label="Navegación de Flow Sell"><BrandMark light/><div><a href="#planes">Planes</a><Link to="/guide">Guía de uso</Link><a href="#ingresar" className="fs-nav-cta">Ingresar <FiArrowRight/></a></div></nav>
    <div className="fs-hero"><section className="fs-story"><span className="fs-kicker"><FiZap/> Tu operación, en movimiento</span><h1>Más tiempo para vender.<br/><span>Menos tareas repetidas.</span></h1><p>Reuní tus publicaciones, mensajes posventa y estadísticas de Mercado Libre en un espacio pensado para trabajar mejor.</p><div className="fs-benefits"><div><FiMessageCircle/><strong>Mensajes a tiempo</strong><span>Flujos por publicación y variante.</span></div><div><FiBarChart2/><strong>Ventas a la vista</strong><span>Entendé tu operación con datos.</span></div><div><FiLayers/><strong>Todo en su lugar</strong><span>Plantillas listas para reutilizar.</span></div></div><div className="fs-flow-preview" aria-label="Ejemplo de automatización"><span>Así funciona</span><ol><li><b>01</b>Venta pagada</li><li><b>02</b>Tu flujo configurado</li><li><b>03</b>Mensaje posventa</li></ol><small>Los envíos dependen de los permisos y reglas de Mercado Libre.</small></div></section>
    <section className="fs-signin" id="ingresar"><span className="fs-eyebrow">Bienvenido a tu panel</span><h2>Ingresá a Flow Sell</h2><p>Conectá la cuenta con la que vendés. Empezá con el plan Gratuito y ampliá cuando lo necesites.</p>{params.has('error')&&<div className="form-alert form-alert--error" role="alert">{params.get('error')==='session'?'No pudimos recuperar tu sesión. Iniciá nuevamente desde este botón. Si volvés a esta pantalla, contactá a soporte para revisar el acceso.':'No se pudo completar el acceso. Iniciá nuevamente desde este botón; no reutilices la dirección de retorno de Mercado Libre. Si persiste, contactá a soporte.'}</div>}<a href={apiUrl('/api/auth/login')} className="meli-login-button"><span className="meli-login-button__handshake">ML</span><span>Continuar con Mercado Libre</span><FiArrowRight/></a>
    <div className="fs-signin-security"><FiShield/><div><strong>Tu contraseña se queda en Mercado Libre</strong><p>La conexión se autoriza en su plataforma. Después del ingreso, revisás y aceptás los documentos de Flow Sell para comenzar.</p></div></div><p className="fs-signin-legal">Antes de conectar tu cuenta, conocé nuestra <Link to="/privacy">Política de privacidad</Link> y los <Link to="/terms">Términos y Condiciones</Link>.</p><a className="button button--secondary button--full" href={SUPPORT_WHATSAPP_URL} target="_blank" rel="noreferrer"><FiMessageCircle/> Ayuda para ingresar</a><small className="fs-signin-note">Sin tarjeta para probar · Cuenta de vendedor requerida</small></section></div>
    </div><section className="fs-pricing" id="planes"><div className="fs-section-intro"><span className="fs-eyebrow">Capacidad para cada etapa</span><h2>Un plan que acompañe tu negocio</h2><p>Probá gratis. Para contratar Premium o Plus, ingresá a tu cuenta y coordiná con nosotros.</p></div><PlanCards/><p className="fs-price-note">Precios mensuales en USD. El importe final, impuestos, moneda de cobro y vigencia se confirman antes del pago por soporte. Sin cobros automáticos dentro de la app.</p></section>
    <section className="fs-landing-help"><div><span className="fs-eyebrow">Empezá con claridad</span><h2>No hace falta adivinar el siguiente paso.</h2><p>La guía explica cada sección, qué cambió y cómo preparar tu primera automatización.</p></div><Link className="button button--primary" to="/guide">Explorar la guía <FiArrowRight/></Link></section>
    <footer className="fs-landing-footer"><BrandMark/><p>© {new Date().getFullYear()} Flow Sell</p><div><Link to="/privacy">Privacidad</Link><Link to="/terms">Términos y Condiciones</Link><a href={SUPPORT_WHATSAPP_URL} target="_blank" rel="noreferrer">Soporte</a></div><small>Servicio independiente. No somos Mercado Libre ni garantizamos resultados comerciales.</small></footer>
  </main>;
}
